### ISSUE TITLE
Shape resize to magnitude from selected objects in an area

### ISSUE THREAD

**Issue by uppalavamsi** [NationalSecurityAgency/qgis-shapetools-plugin#11]
It would be good to have the option to magnify selected shape objects on-the-go, to have flexibility visualization at different zoom levels.

**Comment by hamiltoncj** [comment]
Since Shape Tools creates actual physical polygons, there is no way to have them dynamically resize on the fly. The only way I could think of doing this would be within a style. I don't know if it is possible or not. Right now my focus is not with styling but if I ever get more time I may look into it. For now I am going to close the ticket.
