### ISSUE TITLE
Azimuth/Distance fields not pickable in QGIS3

### ISSUE THREAD

**Issue by gisresolute** [NationalSecurityAgency/qgis-shapetools-plugin#13]
![image](https://user-images.githubusercontent.com/39177877/39903774-6f0845c0-5507-11e8-89c5-2060004a50da.png)
I cant pick the distance and azimuth fields in QGIS3 but can in QGIS2

**Comment by hamiltoncj** [comment]
@gisresolute Can you provide some more information? I just tested it on my machine and I don't have any issues. Do you have a point or line layer selected and is it enabled for editing? Are you on Windows or Linux? Are you using the latest QGIS 3.0.2?

**Comment by gisresolute** [comment]
HI,

Thanks for your swift reply,

Yes  I have a point layer enabled for editing, running on Windows 10, using QGIS 3.0.2, im pulling a view from MSSQL, I think it might be do with that.

If I save that layer as a SHP file it works fine but reading from the MSSQL I get this python error:

2018-05-14T07:50:01 WARNING Traceback (most recent call last):
File "C:/Users/cfranklin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\shapetools\vector2Shape.py", line 155, in showEvent
self.findFields()
File "C:/Users/cfranklin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\shapetools\vector2Shape.py", line 162, in findFields
if layer:
SystemError: error return without exception set

But running the tool in QGIS 2.18.19 I get no error on the same MSSQL dataset.

Subset of dataset attached.

Kind Regards

[RDG-Logo-Tagline]

Chris Franklin
Senior GIS Officer
Level 2, Australia Place, 15 - 17 William Street
Perth, Western Australia 6000
T: +61 8 9261 6100  |  D: +61 8 9261 6127 |  M: +61 420 665660
www.rml.com.au<http://www.rml.com.au/>


Please consider the environment before printing this email.
This email and any attached files are confidential and may be legally privileged. If you are not the intended recipient, any disclosure, reproduction, copying, distribution, or other dissemination or use of this communication is strictly prohibited. If you have received this transmission in error, please notify the sender immediately and then delete this email. Email transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore is in no way liable for any errors or omissions in the content of this message, which may arise as a result of email transmission. If verification is required, please request a hard copy.

**Comment by hamiltoncj** [comment]
@gisresolute I am at FOSS4G NA this week and am not going to have much time to take a look at the issue, but I have been following the QGIS developers groupt. A few days ago there was a person who had a similar issue with MSSQL and QGIS 3. I'm thinking there may be a problem with the MSSQL driver and will probably be fixed in the next release, but I should probably report what you found to the QGIS developers group.

**Comment by hamiltoncj** [comment]
@gisresolute I wish I had an answer for you. I have taken a look at the code and do not see where there could be a problem. I can't replicate it primarily because I don't have an MSSQL database. I have seen some issues with MSSQL in the qgis-developer's group so I am thinking it is a problem with QGIS 3 and MSSQL. If there is any way you can create a small data set that replicates the problem so that I can test it, that might help identify whether it is a plugin problem or QGIS 3 problem.
