### ISSUE TITLE
Please do not include external libs

### ISSUE THREAD

**Issue by pcav** [NationalSecurityAgency/qgis-shapetools-plugin#34]
to avoid duplication of code, etc.
Since geographiclib is of rather general use, it would be probably appropriate to include it in the installers instead.

**Comment by Asratum** [comment]
Submitted a ticked on OSGeo4W for library to be included:
https://trac.osgeo.org/osgeo4w/ticket/621

**Comment by pcav** [comment]
Thanks!

**Comment by hamiltoncj** [comment]
@pcav @Asratum 
I certainly welcome geographiclib to be an integral part of QGIS, but it needs to be included by default and not one of the optional packages in both the OSGeo4W installer as well as the QGIS standalone installers. 

It may have been better to have considered the C version of geographiclib with python wrappers. The C version is probably faster and is more complete. What do you think?

**Comment by pcav** [comment]
it is now included, my interpretation is that it will be present in the installers for the next releases, both point and major. better to make sure, asking in qgis-dev or in the ticket.
as for the C verison, should this be included as a dependency, or?

**Comment by hamiltoncj** [comment]
@pcav @Asratum 
I am personally a little confused with all the versions of geographiclib. The C++ version is by far the most complete with all kinds of capabilities which I would make use of if I had them. See:

https://geographiclib.sourceforge.io/html/index.html

The other language implementations just include the primary geodesic functionality. For Python see

https://geographiclib.sourceforge.io/html/python/code.html

For the C++ version notice all the utility functions as well is gravity, geoid height, magnetic models, etc, but I don't know if there are python wrappers for all of these and actually I haven't worked with interfacing C++ to python so I don't know how complicated that is. PROJ now includes at least part of geographiclib as well and probably has everything that the pure python version has. If python wrappers could be included with PROJ then the extra python library might not be needed.

If someone wanted to investigate the best solution for including geographiclib that would be great. I am not sure including the Python version is the best option.

**Comment by hamiltoncj** [comment]
@pcav Just to close out this issue, and since geographiclib has been included into QGIS, I have taken some steps to get away from including the library. Because I have to support the older versions of QGIS I still have geographiclib included, but I first check to see if QGIS has the library or not before I include the external lib. Once I no longer support the older QGIS versions with Shape Tools plugin updates, then I will drop my version of geographiclib.

For our QGIS users I consider it unacceptable for a plugin to require the user to install additional libraries into QGIS so I try to avoid that,. If there is some capability that is really needed by one of my plugins that requires a library not included with QGIS, then it is better for my users to include the library with the plugin. I know that is not your preference, but my main objective it to make it easy for my users.
